export const SET_SHOW_ADD_FORM_ACTION = 'SET_SHOW_ADD_FORM_ACTION';
export const SET_FILTER_UNDONE_ACTION = 'SET_FILTER_UNDONE_ACTION';
export const ADD_TODO_ACTION = 'ADD_TODO_ACTION';
export const CHANGE_TODO_DONE_ACTION = 'CHANGE_TODO_DONE_ACTION';
export const DELETE_TODO_ACTION = 'DELETE_TODO_ACTION';
